#!/bin/bash
# k8s-bootstrap-ubuntu

osDist=$(hostnamectl | awk '/Operating System/ {print $3}' | tr 'A-Z' 'a-z')
if [[ "$osDist" != "ubuntu" ]]; then
    echo"==> This $0 script only runs on Ubuntu"
    exit 1
fi

echo "==> Updated /etc/hosts"
sudo sed -i "/^127\.0\.1\.1.*/d" /etc/hosts
sudo sed -i "/^10\.11\.12\.2.*/d" /etc/hosts
sudo sed -i "/^10\.11\.12\.3.*/d" /etc/hosts
sudo bash -c 'cat >> /etc/hosts' << EOF
10.11.12.2    k2
10.11.12.3    k3 
EOF

echo "==> Disable swap"
sudo swapoff -a
sudo bash -c 'sed -ri "s/^(.*swap.*)$/#\1/" /etc/fstab'
# Note: Ubuntu runs AppArmour by default, so no need to worry about SELinux
#sudo setenforce 0

echo "==> Update IP Tables"
sudo bash -c 'cat > /etc/sysctl.d/k8s.conf' << EOF
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
EOF
sudo sysctl --system

echo "==> Update system packages and install and enable Docker"
sudo apt-get update 
sudo apt-get install -y docker.io
sudo systemctl start docker
sudo systemctl enable docker
sudo systemctl status docker

echo "==> Setting up Kubernetes apt repo, and installing"
sudo apt-get install -y apt-transport-https curl software-properties-common
sudo apt-get install -y docker.io
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
sudo apt-add-repository "deb http://apt.kubernetes.io/ kubernetes-xenial main"
sudo apt-get update
sudo apt-get install -y kubelet kubeadm kubectl

echo "==> Enable and start Kubernetes "
sudo systemctl enable kubelet && sudo systemctl start kubelet

#echo "==> Setting Cgroup Driver"
## docker info | -i cgroup
#sudo mkdir -p /etc/systemd/system/kubelet.service.d
#sudo bash -c 'cat > /etc/systemd/system/kubelet.service.d/10-kubeadm.conf' << EOF
#[Service]
#Environment="KUBELET_CGROUP_ARGS=--cgroup-driver=systemd"
#EOF

echo "==> Reload daemon and restart Kubernetes"
sudo systemctl daemon-reload && sudo systemctl restart kubelet

echo "Updating /root/.bashrc"
sudo bash -c 'echo "export PATH=\$PATH:/usr/local/bin" >> /root/.bashrc'
sudo bash -c 'echo -e "alias vi=vim\nalias h=history" >> /root/.bashrc'

exit 0
